apiVersion: apps/v1
kind: Deployment
metadata:
  name: bankapp-deployment
  namespace: bankapp-namespace
  labels:
    app: bankapp-deploy

spec:
  replicas: 2
  selector:
    matchLabels:
      app: bankapp-deploy
  template:
    metadata:
      name: bankapp-pod
      namespace: bankapp-namespace
      labels:
        app: bankapp-deploy
    spec:
      containers:
      - name: bankapp-container
        image: 2604manishyadav/bankapp-eks:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" 
        ports:
        - containerPort: 8080

